# Generated by Django 5.1.2 on 2024-10-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('token', models.TextField(default=None)),
                ('recipient_list', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_mail_status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('firebase_response', models.TextField(blank=True, null=True)),
                ('mail_action', models.BooleanField(default=False)),
                ('firebase_action', models.BooleanField(default=False)),
                ('is_schedule', models.BooleanField(default=False)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('schedule_status', models.IntegerField(default=0)),
            ],
        ),
    ]
