# Generated by Django 5.1 on 2024-11-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="email_service_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="email",
            name="email_service_api_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="email",
            name="email_service_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
